// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: airports/v2/airport_service.proto

package airportsv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/kongken/kapi/pkg/proto/airports/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AirportServiceName is the fully-qualified name of the AirportService service.
	AirportServiceName = "airports.v2.AirportService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AirportServiceGetFlightsProcedure is the fully-qualified name of the AirportService's GetFlights
	// RPC.
	AirportServiceGetFlightsProcedure = "/airports.v2.AirportService/GetFlights"
	// AirportServiceGetWeatherProcedure is the fully-qualified name of the AirportService's GetWeather
	// RPC.
	AirportServiceGetWeatherProcedure = "/airports.v2.AirportService/GetWeather"
)

// AirportServiceClient is a client for the airports.v2.AirportService service.
type AirportServiceClient interface {
	GetFlights(context.Context, *connect.Request[v2.GetFlightsRequest]) (*connect.Response[v2.GetFlightsResponse], error)
	GetWeather(context.Context, *connect.Request[v2.GetWeatherRequest]) (*connect.Response[v2.GetWeatherResponse], error)
}

// NewAirportServiceClient constructs a client for the airports.v2.AirportService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAirportServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AirportServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	airportServiceMethods := v2.File_airports_v2_airport_service_proto.Services().ByName("AirportService").Methods()
	return &airportServiceClient{
		getFlights: connect.NewClient[v2.GetFlightsRequest, v2.GetFlightsResponse](
			httpClient,
			baseURL+AirportServiceGetFlightsProcedure,
			connect.WithSchema(airportServiceMethods.ByName("GetFlights")),
			connect.WithClientOptions(opts...),
		),
		getWeather: connect.NewClient[v2.GetWeatherRequest, v2.GetWeatherResponse](
			httpClient,
			baseURL+AirportServiceGetWeatherProcedure,
			connect.WithSchema(airportServiceMethods.ByName("GetWeather")),
			connect.WithClientOptions(opts...),
		),
	}
}

// airportServiceClient implements AirportServiceClient.
type airportServiceClient struct {
	getFlights *connect.Client[v2.GetFlightsRequest, v2.GetFlightsResponse]
	getWeather *connect.Client[v2.GetWeatherRequest, v2.GetWeatherResponse]
}

// GetFlights calls airports.v2.AirportService.GetFlights.
func (c *airportServiceClient) GetFlights(ctx context.Context, req *connect.Request[v2.GetFlightsRequest]) (*connect.Response[v2.GetFlightsResponse], error) {
	return c.getFlights.CallUnary(ctx, req)
}

// GetWeather calls airports.v2.AirportService.GetWeather.
func (c *airportServiceClient) GetWeather(ctx context.Context, req *connect.Request[v2.GetWeatherRequest]) (*connect.Response[v2.GetWeatherResponse], error) {
	return c.getWeather.CallUnary(ctx, req)
}

// AirportServiceHandler is an implementation of the airports.v2.AirportService service.
type AirportServiceHandler interface {
	GetFlights(context.Context, *connect.Request[v2.GetFlightsRequest]) (*connect.Response[v2.GetFlightsResponse], error)
	GetWeather(context.Context, *connect.Request[v2.GetWeatherRequest]) (*connect.Response[v2.GetWeatherResponse], error)
}

// NewAirportServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAirportServiceHandler(svc AirportServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	airportServiceMethods := v2.File_airports_v2_airport_service_proto.Services().ByName("AirportService").Methods()
	airportServiceGetFlightsHandler := connect.NewUnaryHandler(
		AirportServiceGetFlightsProcedure,
		svc.GetFlights,
		connect.WithSchema(airportServiceMethods.ByName("GetFlights")),
		connect.WithHandlerOptions(opts...),
	)
	airportServiceGetWeatherHandler := connect.NewUnaryHandler(
		AirportServiceGetWeatherProcedure,
		svc.GetWeather,
		connect.WithSchema(airportServiceMethods.ByName("GetWeather")),
		connect.WithHandlerOptions(opts...),
	)
	return "/airports.v2.AirportService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AirportServiceGetFlightsProcedure:
			airportServiceGetFlightsHandler.ServeHTTP(w, r)
		case AirportServiceGetWeatherProcedure:
			airportServiceGetWeatherHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAirportServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAirportServiceHandler struct{}

func (UnimplementedAirportServiceHandler) GetFlights(context.Context, *connect.Request[v2.GetFlightsRequest]) (*connect.Response[v2.GetFlightsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("airports.v2.AirportService.GetFlights is not implemented"))
}

func (UnimplementedAirportServiceHandler) GetWeather(context.Context, *connect.Request[v2.GetWeatherRequest]) (*connect.Response[v2.GetWeatherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("airports.v2.AirportService.GetWeather is not implemented"))
}
