environment: "local"
http_port: 8080

log:
  level: "info"
  format: "text"
  add_source: false

otel: {}

szx:
  sync_interval: "5m"

store:
  redis:
    default:
      addr: "127.0.0.1:6379"
      password: ""
      db: 0
  s3:
    flight:
      endpoint: ""
      access_key_id: ""
      secret_access_key: ""
      region: "us-east-1"
      bucket: ""
      use_ssl: true
