// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: airports/v2/flight.proto

package airportsv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Airport       string                 `protobuf:"bytes,1,opt,name=airport,proto3" json:"airport,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	FlightNo      string                 `protobuf:"bytes,6,opt,name=flight_no,json=flightNo,proto3" json:"flight_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightsRequest) Reset() {
	*x = GetFlightsRequest{}
	mi := &file_airports_v2_flight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsRequest) ProtoMessage() {}

func (x *GetFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_airports_v2_flight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsRequest.ProtoReflect.Descriptor instead.
func (*GetFlightsRequest) Descriptor() ([]byte, []int) {
	return file_airports_v2_flight_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlightsRequest) GetAirport() string {
	if x != nil {
		return x.Airport
	}
	return ""
}

func (x *GetFlightsRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *GetFlightsRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *GetFlightsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetFlightsRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GetFlightsRequest) GetFlightNo() string {
	if x != nil {
		return x.FlightNo
	}
	return ""
}

type GetFlightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Airport       string                 `protobuf:"bytes,2,opt,name=airport,proto3" json:"airport,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Query         *FlightsQuery          `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Total         int32                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*Flight              `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	Raw           *structpb.Struct       `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightsResponse) Reset() {
	*x = GetFlightsResponse{}
	mi := &file_airports_v2_flight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsResponse) ProtoMessage() {}

func (x *GetFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_airports_v2_flight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsResponse.ProtoReflect.Descriptor instead.
func (*GetFlightsResponse) Descriptor() ([]byte, []int) {
	return file_airports_v2_flight_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlightsResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetFlightsResponse) GetAirport() string {
	if x != nil {
		return x.Airport
	}
	return ""
}

func (x *GetFlightsResponse) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetFlightsResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *GetFlightsResponse) GetQuery() *FlightsQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetFlightsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFlightsResponse) GetItems() []*Flight {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetFlightsResponse) GetRaw() *structpb.Struct {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FlightsQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	FlightNo      string                 `protobuf:"bytes,5,opt,name=flight_no,json=flightNo,proto3" json:"flight_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightsQuery) Reset() {
	*x = FlightsQuery{}
	mi := &file_airports_v2_flight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightsQuery) ProtoMessage() {}

func (x *FlightsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_airports_v2_flight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightsQuery.ProtoReflect.Descriptor instead.
func (*FlightsQuery) Descriptor() ([]byte, []int) {
	return file_airports_v2_flight_proto_rawDescGZIP(), []int{2}
}

func (x *FlightsQuery) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FlightsQuery) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *FlightsQuery) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FlightsQuery) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *FlightsQuery) GetFlightNo() string {
	if x != nil {
		return x.FlightNo
	}
	return ""
}

type Flight struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FlightNumbers        []string               `protobuf:"bytes,1,rep,name=flight_numbers,json=flightNumbers,proto3" json:"flight_numbers,omitempty"`
	AirlineLogos         []string               `protobuf:"bytes,2,rep,name=airline_logos,json=airlineLogos,proto3" json:"airline_logos,omitempty"`
	PlannedDepartureTime string                 `protobuf:"bytes,3,opt,name=planned_departure_time,json=plannedDepartureTime,proto3" json:"planned_departure_time,omitempty"`
	PlannedArrivalTime   string                 `protobuf:"bytes,4,opt,name=planned_arrival_time,json=plannedArrivalTime,proto3" json:"planned_arrival_time,omitempty"`
	ActualDepartureTime  string                 `protobuf:"bytes,5,opt,name=actual_departure_time,json=actualDepartureTime,proto3" json:"actual_departure_time,omitempty"`
	ActualArrivalTime    string                 `protobuf:"bytes,6,opt,name=actual_arrival_time,json=actualArrivalTime,proto3" json:"actual_arrival_time,omitempty"`
	DepartureAirport     string                 `protobuf:"bytes,7,opt,name=departure_airport,json=departureAirport,proto3" json:"departure_airport,omitempty"`
	ArrivalAirport       string                 `protobuf:"bytes,8,opt,name=arrival_airport,json=arrivalAirport,proto3" json:"arrival_airport,omitempty"`
	Terminal             string                 `protobuf:"bytes,9,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Gate                 string                 `protobuf:"bytes,10,opt,name=gate,proto3" json:"gate,omitempty"`
	GateDescription      string                 `protobuf:"bytes,11,opt,name=gate_description,json=gateDescription,proto3" json:"gate_description,omitempty"`
	BaggageBelt          string                 `protobuf:"bytes,12,opt,name=baggage_belt,json=baggageBelt,proto3" json:"baggage_belt,omitempty"`
	CheckInArea          string                 `protobuf:"bytes,13,opt,name=check_in_area,json=checkInArea,proto3" json:"check_in_area,omitempty"`
	CheckInWindow        string                 `protobuf:"bytes,14,opt,name=check_in_window,json=checkInWindow,proto3" json:"check_in_window,omitempty"`
	StatusText           string                 `protobuf:"bytes,15,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	StatusCode           string                 `protobuf:"bytes,16,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	AircraftType         string                 `protobuf:"bytes,17,opt,name=aircraft_type,json=aircraftType,proto3" json:"aircraft_type,omitempty"`
	Raw                  *structpb.Struct       `protobuf:"bytes,18,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_airports_v2_flight_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_airports_v2_flight_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_airports_v2_flight_proto_rawDescGZIP(), []int{3}
}

func (x *Flight) GetFlightNumbers() []string {
	if x != nil {
		return x.FlightNumbers
	}
	return nil
}

func (x *Flight) GetAirlineLogos() []string {
	if x != nil {
		return x.AirlineLogos
	}
	return nil
}

func (x *Flight) GetPlannedDepartureTime() string {
	if x != nil {
		return x.PlannedDepartureTime
	}
	return ""
}

func (x *Flight) GetPlannedArrivalTime() string {
	if x != nil {
		return x.PlannedArrivalTime
	}
	return ""
}

func (x *Flight) GetActualDepartureTime() string {
	if x != nil {
		return x.ActualDepartureTime
	}
	return ""
}

func (x *Flight) GetActualArrivalTime() string {
	if x != nil {
		return x.ActualArrivalTime
	}
	return ""
}

func (x *Flight) GetDepartureAirport() string {
	if x != nil {
		return x.DepartureAirport
	}
	return ""
}

func (x *Flight) GetArrivalAirport() string {
	if x != nil {
		return x.ArrivalAirport
	}
	return ""
}

func (x *Flight) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

func (x *Flight) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *Flight) GetGateDescription() string {
	if x != nil {
		return x.GateDescription
	}
	return ""
}

func (x *Flight) GetBaggageBelt() string {
	if x != nil {
		return x.BaggageBelt
	}
	return ""
}

func (x *Flight) GetCheckInArea() string {
	if x != nil {
		return x.CheckInArea
	}
	return ""
}

func (x *Flight) GetCheckInWindow() string {
	if x != nil {
		return x.CheckInWindow
	}
	return ""
}

func (x *Flight) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *Flight) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Flight) GetAircraftType() string {
	if x != nil {
		return x.AircraftType
	}
	return ""
}

func (x *Flight) GetRaw() *structpb.Struct {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_airports_v2_flight_proto protoreflect.FileDescriptor

const file_airports_v2_flight_proto_rawDesc = "" +
	"\n" +
	"\x18airports/v2/flight.proto\x12\vairports.v2\x1a\x1cgoogle/protobuf/struct.proto\"\xa4\x01\n" +
	"\x11GetFlightsRequest\x12\x18\n" +
	"\aairport\x18\x01 \x01(\tR\aairport\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\x12\x1b\n" +
	"\tflight_no\x18\x06 \x01(\tR\bflightNo\"\x9d\x02\n" +
	"\x12GetFlightsResponse\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\aairport\x18\x02 \x01(\tR\aairport\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12/\n" +
	"\x05query\x18\x05 \x01(\v2\x19.airports.v2.FlightsQueryR\x05query\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x05R\x05total\x12)\n" +
	"\x05items\x18\a \x03(\v2\x13.airports.v2.FlightR\x05items\x12)\n" +
	"\x03raw\x18\b \x01(\v2\x17.google.protobuf.StructR\x03raw\"\x85\x01\n" +
	"\fFlightsQuery\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1b\n" +
	"\tflight_no\x18\x05 \x01(\tR\bflightNo\"\xd2\x05\n" +
	"\x06Flight\x12%\n" +
	"\x0eflight_numbers\x18\x01 \x03(\tR\rflightNumbers\x12#\n" +
	"\rairline_logos\x18\x02 \x03(\tR\fairlineLogos\x124\n" +
	"\x16planned_departure_time\x18\x03 \x01(\tR\x14plannedDepartureTime\x120\n" +
	"\x14planned_arrival_time\x18\x04 \x01(\tR\x12plannedArrivalTime\x122\n" +
	"\x15actual_departure_time\x18\x05 \x01(\tR\x13actualDepartureTime\x12.\n" +
	"\x13actual_arrival_time\x18\x06 \x01(\tR\x11actualArrivalTime\x12+\n" +
	"\x11departure_airport\x18\a \x01(\tR\x10departureAirport\x12'\n" +
	"\x0farrival_airport\x18\b \x01(\tR\x0earrivalAirport\x12\x1a\n" +
	"\bterminal\x18\t \x01(\tR\bterminal\x12\x12\n" +
	"\x04gate\x18\n" +
	" \x01(\tR\x04gate\x12)\n" +
	"\x10gate_description\x18\v \x01(\tR\x0fgateDescription\x12!\n" +
	"\fbaggage_belt\x18\f \x01(\tR\vbaggageBelt\x12\"\n" +
	"\rcheck_in_area\x18\r \x01(\tR\vcheckInArea\x12&\n" +
	"\x0fcheck_in_window\x18\x0e \x01(\tR\rcheckInWindow\x12\x1f\n" +
	"\vstatus_text\x18\x0f \x01(\tR\n" +
	"statusText\x12\x1f\n" +
	"\vstatus_code\x18\x10 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\raircraft_type\x18\x11 \x01(\tR\faircraftType\x12)\n" +
	"\x03raw\x18\x12 \x01(\v2\x17.google.protobuf.StructR\x03rawB:Z8github.com/kongken/kapi/pkg/proto/airports/v2;airportsv2b\x06proto3"

var (
	file_airports_v2_flight_proto_rawDescOnce sync.Once
	file_airports_v2_flight_proto_rawDescData []byte
)

func file_airports_v2_flight_proto_rawDescGZIP() []byte {
	file_airports_v2_flight_proto_rawDescOnce.Do(func() {
		file_airports_v2_flight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_airports_v2_flight_proto_rawDesc), len(file_airports_v2_flight_proto_rawDesc)))
	})
	return file_airports_v2_flight_proto_rawDescData
}

var file_airports_v2_flight_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_airports_v2_flight_proto_goTypes = []any{
	(*GetFlightsRequest)(nil),  // 0: airports.v2.GetFlightsRequest
	(*GetFlightsResponse)(nil), // 1: airports.v2.GetFlightsResponse
	(*FlightsQuery)(nil),       // 2: airports.v2.FlightsQuery
	(*Flight)(nil),             // 3: airports.v2.Flight
	(*structpb.Struct)(nil),    // 4: google.protobuf.Struct
}
var file_airports_v2_flight_proto_depIdxs = []int32{
	2, // 0: airports.v2.GetFlightsResponse.query:type_name -> airports.v2.FlightsQuery
	3, // 1: airports.v2.GetFlightsResponse.items:type_name -> airports.v2.Flight
	4, // 2: airports.v2.GetFlightsResponse.raw:type_name -> google.protobuf.Struct
	4, // 3: airports.v2.Flight.raw:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_airports_v2_flight_proto_init() }
func file_airports_v2_flight_proto_init() {
	if File_airports_v2_flight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_airports_v2_flight_proto_rawDesc), len(file_airports_v2_flight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_airports_v2_flight_proto_goTypes,
		DependencyIndexes: file_airports_v2_flight_proto_depIdxs,
		MessageInfos:      file_airports_v2_flight_proto_msgTypes,
	}.Build()
	File_airports_v2_flight_proto = out.File
	file_airports_v2_flight_proto_goTypes = nil
	file_airports_v2_flight_proto_depIdxs = nil
}
