// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: airports/v2/service.proto

package airportsv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_airports_v2_service_proto protoreflect.FileDescriptor

const file_airports_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x19airports/v2/service.proto\x12\vairports.v2\x1a\x18airports/v2/flight.proto\x1a\x19airports/v2/weather.proto2\xae\x01\n" +
	"\x0eAirportService\x12M\n" +
	"\n" +
	"GetFlights\x12\x1e.airports.v2.GetFlightsRequest\x1a\x1f.airports.v2.GetFlightsResponse\x12M\n" +
	"\n" +
	"GetWeather\x12\x1e.airports.v2.GetWeatherRequest\x1a\x1f.airports.v2.GetWeatherResponseB:Z8github.com/kongken/kapi/pkg/proto/airports/v2;airportsv2b\x06proto3"

var file_airports_v2_service_proto_goTypes = []any{
	(*GetFlightsRequest)(nil),  // 0: airports.v2.GetFlightsRequest
	(*GetWeatherRequest)(nil),  // 1: airports.v2.GetWeatherRequest
	(*GetFlightsResponse)(nil), // 2: airports.v2.GetFlightsResponse
	(*GetWeatherResponse)(nil), // 3: airports.v2.GetWeatherResponse
}
var file_airports_v2_service_proto_depIdxs = []int32{
	0, // 0: airports.v2.AirportService.GetFlights:input_type -> airports.v2.GetFlightsRequest
	1, // 1: airports.v2.AirportService.GetWeather:input_type -> airports.v2.GetWeatherRequest
	2, // 2: airports.v2.AirportService.GetFlights:output_type -> airports.v2.GetFlightsResponse
	3, // 3: airports.v2.AirportService.GetWeather:output_type -> airports.v2.GetWeatherResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_airports_v2_service_proto_init() }
func file_airports_v2_service_proto_init() {
	if File_airports_v2_service_proto != nil {
		return
	}
	file_airports_v2_flight_proto_init()
	file_airports_v2_weather_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_airports_v2_service_proto_rawDesc), len(file_airports_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_airports_v2_service_proto_goTypes,
		DependencyIndexes: file_airports_v2_service_proto_depIdxs,
	}.Build()
	File_airports_v2_service_proto = out.File
	file_airports_v2_service_proto_goTypes = nil
	file_airports_v2_service_proto_depIdxs = nil
}
